version: '3.8'

services: 

# Backend API
  smart-brain:
    container_name: backend
    # image: node:stretch
    build: ./
    command: npm start
    working_dir: /usr/src/smart-brain
    environment: 
      POSTGRES_URI: postgres://sally:secret@postgres:5432/smart-brain-docker
    links:
      - postgres
    ports: 
      - "3000:3000"
    volumes:
      - ./:/usr/src/smart-brain
  
# Postgres
  postgres: 
    # container_name: postgres
    environment: 
      POSTGRES_USER: sally
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: smart-brain-docker
      POSTGRES_HOST: postgres
    build: ./postgres
    ports:
      - "5431:5432"

